name: Update README Activity

on:
  schedule:
    - cron: '0 * * * *' # 每小時自動執行一次
  workflow_dispatch: # 支援在 Actions 頁面手動觸發
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README Activity
        uses: jamesgeorge007/github-activity-readme@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          COMMIT_MSG: 'chore: auto-update README activity log [skip ci]'
          MAX_LINES: 5
